
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UPS.SpaceX.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Giver
{

    public string email { get; set; }

    public string desk { get; set; }

    public System.DateTime date { get; set; }

    public int karmaPoints { get; set; }

    public bool isAvailable { get; set; }

}

}
