

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UPS.SpaceX.DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UPSSpaceXEntities : DbContext
{
    public UPSSpaceXEntities()
        : base("name=UPSSpaceXEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Donor> Donors { get; set; }

    public virtual DbSet<Desk> Desks { get; set; }

    public virtual DbSet<Giver> Givers { get; set; }

    public virtual DbSet<Recipient> Recipients { get; set; }

}

}

